services:
  api:
    container_name: bank-village-container
    image: bank-village-image
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    # Mount host directory to docker container to support watch mode
    volumes:
      - .:/app
      # This ensures that the NestJS container manages the node_modules folder
      # rather than synchronizes it with the host machine
      - /app/node_modules
    env_file:
      - .env
    ports:
      - 4000:4000