version: '3'
services:
  api:
    platform: linux/amd64
    container_name: bank-village-container
    image: bank-village-image
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    # Mount host directory to docker container to support watch mode
    env_file:
      - .env
    ports:
      - 4000:4000
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
      
volumes:
  postgres-data:
