[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "18"

[build]
  publish = ".output/public"
  command = "pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
